# Generated by Django 4.2.5 on 2023-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('is_alive', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
